### ISSUE TITLE
Useless instance reference not in use.

### ISSUE THREAD

**Issue by arantesxyz** [Kewilleen/TabsTag#1]
Also static instance of the plugin is considered a bad practice according to Spigot's beginner programming mistakes thread: https://www.spigotmc.org/threads/beginner-programming-mistakes-and-why-youre-making-them.278876/

https://github.com/Kewilleen/TabsTag/blob/853cbcb5fdef7e03268d7b2c892b514db8a443e0/src/me/kewi/TabsTag.java#L27

**Comment by Kewilleen** [comment]
Hi @arantesxyz ,

Thanks to notify me. I'll do a new commit.
